### PR TITLE
Create OpenMowerMainboard.pdf

### PR DESCRIPTION
**Pull request by mulcmu**
Added a PDF of the Kicad schematic for online viewing.

### CODE REVIEW

**Comment by rfvermut** [comment]
Will try to automate this in https://github.com/ClemensElflein/OpenMower/pull/25

Will appear in https://clemenselflein.github.io/OpenMower/

**Comment by ClemensElflein** [comment]
Thanks for the PR, but @rfvermut has automated this process, so that we don't need to manually keep these up to date. Therefore, I'm closing this PR.

**Comment by mulcmu** [comment]
The `kibot` automation looks pretty slick.  I'm going to have to add that to some of my repositories now.

**Comment by rfvermut** [comment]
dev branch has better GH workflows, just refactored

**Pull request closed without merging**
